import type { Policy, PolicyStatus, PolicyCategory, Country } from '@/lib/types';

export const COUNTRIES: Country[] = [
  // Southeast Asia
  { code: "ID", name: "Indonesia", region: "Southeast Asia" },
  { code: "PH", name: "Philippines", region: "Southeast Asia" },
  { code: "VN", name: "Vietnam", region: "Southeast Asia" },
  { code: "TH", name: "Thailand", region: "Southeast Asia" },
  { code: "MY", name: "Malaysia", region: "Southeast Asia" },
  { code: "SG", name: "Singapore", region: "Southeast Asia" },
  { code: "KH", name: "Cambodia", region: "Southeast Asia" },
  { code: "LA", name: "Laos", region: "Southeast Asia" },
  { code: "MM", name: "Myanmar", region: "Southeast Asia" },
  { code: "BN", name: "Brunei", region: "Southeast Asia" },
  // South Asia
  { code: "IN", name: "India", region: "South Asia" },
  { code: "PK", name: "Pakistan", region: "South Asia" },
  { code: "BD", name: "Bangladesh", region: "South Asia" },
  { code: "LK", name: "Sri Lanka", region: "South Asia" },
  { code: "NP", name: "Nepal", region: "South Asia" },
  { code: "BT", name: "Bhutan", region: "South Asia" },
  // East Asia
  { code: "JP", name: "Japan", region: "East Asia" },
  { code: "KR", name: "South Korea", region: "East Asia" },
  { code: "CN", name: "China", region: "East Asia" },
  { code: "TW", name: "Taiwan", region: "East Asia" },
  { code: "MN", name: "Mongolia", region: "East Asia" },
  // Oceania
  { code: "AU", name: "Australia", region: "Oceania" },
  { code: "NZ", name: "New Zealand", region: "Oceania" },
  { code: "FJ", name: "Fiji", region: "Oceania" },
  { code: "PG", name: "Papua New Guinea", region: "Oceania" },
  { code: "SB", name: "Solomon Islands", region: "Oceania" },
];

export const REGIONS: string[] = [
  ...new Set(COUNTRIES.map(c => c.region))
].sort();

export const CATEGORIES: PolicyCategory[] = [
  "Plastic Ban",
  "EPR",
  "Waste Management",
  "Circular Economy",
];

export const STATUSES: PolicyStatus[] = [
  "In Force",
  "Proposed",
  "Phased",
  "Repealed",
];

export const POLICIES: Policy[] = [
  {
    id: "phil-2024-01",
    year: 2024,
    country: "PH",
    title: "Single-Use Plastics Regulation Bill",
    summary: "Pending legislation on comprehensive single-use plastic use policies nationwide",
    category: "Plastic Ban",
    instrument: "Bill",
    level: "National",
    status: "Proposed",
    authority: "Philippine Senate",
    link: "https://congress.gov.ph/",
    language: "English",
  },
  {
    id: "japan-2024-01",
    year: 2024,
    country: "JP",
    title: "Draft Act on Management of Packaging Waste (EPRR)",
    summary: "Establishing extended producer responsibility for packaging waste",
    category: "EPR",
    instrument: "Regulation",
    level: "National",
    status: "Proposed",
    authority: "Ministry of Economy, Trade and Industry (METI)",
    link: "https://www.meti.go.jp/",
    language: "Japanese",
  },
  {
    id: "viet-2023-01",
    year: 2023,
    country: "VN",
    title: "Circular Economy Policy Framework for Plastics",
    summary: "Framework for implementing circular economy principles in plastics management",
    category: "Circular Economy",
    instrument: "Framework",
    level: "National",
    status: "In Force",
    authority: "Ministry of Natural Resources and Environment",
    link: "https://www.monre.gov.vn/",
    language: "Vietnamese",
  },
  {
    id: "sing-2023-01",
    year: 2023,
    country: "SG",
    title: "Disposable Carrier Bag Charge",
    summary: "Mandatory 5-cent minimum charge on single-use plastic bags",
    category: "Plastic Ban",
    instrument: "Regulation",
    level: "National",
    status: "In Force",
    authority: "National Environment Agency (NEA)",
    link: "https://www.nea.gov.sg/",
    language: "English",
  },
  {
    id: "indo-2023-01",
    year: 2023,
    country: "ID",
    title: "Extended Producer Responsibility Act (IGA 11890)",
    summary: "Producer responsibility for end-of-life packaging and waste management",
    category: "EPR",
    instrument: "Act",
    level: "National",
    status: "In Force",
    authority: "Ministry of Environment and Forestry",
    link: "https://www.menlhk.go.id/",
    language: "Indonesian",
  },
  {
    id: "india-2023-01",
    year: 2023,
    country: "IN",
    title: "Plastic Waste Management (Amendment) Rules",
    summary: "Rules and ordinances for plastic waste management and recycling",
    category: "Waste Management",
    instrument: "Rules",
    level: "National",
    status: "In Force",
    authority: "Ministry of Environment, Forest and Climate Change",
    link: "https://www.moef.gov.in/",
    language: "English",
  },
  {
    id: "thai-2022-01",
    year: 2022,
    country: "TH",
    title: "Roadmap on Plastic Waste Management 2018-2030",
    summary: "Comprehensive roadmap for managing plastic waste and reducing single-use plastics",
    category: "Waste Management",
    instrument: "Roadmap",
    level: "National",
    status: "In Force",
    authority: "Ministry of Natural Resources and Environment",
    link: "https://www.mnre.go.th/",
    language: "Thai",
  },
  {
    id: "china-2022-01",
    year: 2022,
    country: "CN",
    title: "National Plastic Waste Reduction Strategy",
    summary: "Targets for reduction of marine plastic waste and microplastics",
    category: "Plastic Ban",
    instrument: "Strategy",
    level: "National",
    status: "In Force",
    authority: "Ministry of Ecology and Environment",
    link: "https://www.mee.gov.cn/",
    language: "Chinese",
  },
  {
    id: "aus-2022-01",
    year: 2022,
    country: "AU",
    title: "Recycling and Waste Reduction Act",
    summary: "Export ban on unprocessed plastic waste, mandatory recycling targets",
    category: "Waste Management",
    instrument: "Act",
    level: "National",
    status: "In Force",
    authority: "Department of Climate Change, Energy, Environment and Water",
    link: "https://www.dcceew.gov.au/",
    language: "English",
  },
  {
    id: "sk-2021-01",
    year: 2021,
    country: "KR",
    title: "National Plastics Plan",
    summary: "Phase plan for plastic consumption reduction and circular economy transition",
    category: "Circular Economy",
    instrument: "Plan",
    level: "National",
    status: "In Force",
    authority: "Ministry of Environment",
    link: "https://www.me.go.kr/",
    language: "Korean",
  },
  {
    id: "mal-2021-01",
    year: 2021,
    country: "MY",
    title: "Roadmap Towards Zero Single-Use Plastics 2018-2030",
    summary: "Multi-stage roadmap for eliminating single-use plastics",
    category: "Plastic Ban",
    instrument: "Roadmap",
    level: "National",
    status: "Phased",
    authority: "Ministry of Environment and Water",
    link: "https://www.kasa.gov.my/",
    language: "Malay",
  },
  {
    id: "nz-2020-01",
    year: 2020,
    country: "NZ",
    title: "Plastic Shipping Bags Ban",
    summary: "Ban on plastic shipping bags and loose-fill polystyrene packaging",
    category: "Plastic Ban",
    instrument: "Regulation",
    level: "National",
    status: "In Force",
    authority: "Ministry for the Environment",
    link: "https://www.mfe.govt.nz/",
    language: "English",
  },
];
